require:
  - rubocop-rake
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  NewCops: enable
Style/Documentation:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Max: 16
RSpec/MultipleExpectations:
  Max: 22
RSpec/ExampleLength:
  Max: 29
RSpec/NestedGroups:
  Max: 4
Metrics/MethodLength:
  Max: 22
Rails/I18nLocaleTexts:
  Enabled: false
