
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: nw_dev

test:
  <<: *default
  database: nw_test

production:
  <<: *default
  database: nauticalwar
  username: nauticalwar
  password: <%= ENV['NAUTICALWAR_DATABASE_PASSWORD'] %>
