name: 'Ruby on Rails CI'
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13-alpine
        ports:
          - '5432:5432'
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: 'postgres://rails:password@localhost:5432/rails_test'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install chrome
        uses: browser-actions/setup-chrome@latest
      - run: chrome --version

      - name: Install xvfb
        run: |
          sudo apt-get update
          sudo apt-get install xvfb

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Set up database schema
        run: bin/rails db:schema:load

      - name: Run tests
        run: xvfb-run --auto-servernum bundle exec rspec

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Setup Bundle Audit
        run: gem install bundle-audit

      - name: Security audit dependencies
        run: bundle exec bundle audit check --update

      - name: Setup Brakeman
        run: gem install brakeman

      - name: Security audit application code
        run: bundle exec brakeman -q -w2

      - name: Setup Rubocop
        run: gem install rubocop

      - name: Lint Ruby files
        run: bundle exec rubocop --parallel
